"""drop per-user sync_interval_minutes, use global setting

Revision ID: 108dfb100a15
Revises: ecadc9c7cab5
Create Date: 2026-07-13 18:47:51.552467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '108dfb100a15'
down_revision: Union[str, None] = 'ecadc9c7cab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_settings', 'sync_interval_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_settings', sa.Column('sync_interval_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
