"""drop per-user window_weeks_ahead and window_days_behind

Revision ID: 76e597def5c6
Revises: 108dfb100a15
Create Date: 2026-07-13 19:52:07.426234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76e597def5c6'
down_revision: Union[str, None] = '108dfb100a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_settings', 'window_weeks_ahead')
    op.drop_column('sync_settings', 'window_days_behind')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_settings', sa.Column('window_days_behind', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sync_settings', sa.Column('window_weeks_ahead', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
